### ISSUE TITLE
No completion in REPL (solved), please update README.org

### ISSUE THREAD

**Issue by ackalker** [clojure-emacs/ac-cider#26]
After installing ac-cider and updating my ~/.emacs according to README.org, I was unable to use auto-complete in CIDER REPL.

I tried changing in ~/.emacs:

``` elisp
(eval-after-load "auto-complete"
  '(add-to-list 'ac-modes 'cider-mode))
```

to:

``` elisp
(eval-after-load "auto-complete"
  '(progn
     (add-to-list 'ac-modes 'cider-mode)
     (add-to-list 'ac-modes 'cider-repl-mode))))
```

and now I have auto-complete support in the REPL as well.
Could you please update README.doc for others to use, or is there perhaps a reason (lingering effects of issue #5) to not document this?

**Comment by alexander-yakushev** [comment]
What do you mean by crossed?:) Did I make a mistake with my edit?

**Comment by ackalker** [comment]
No, no :-) I meant that I was editing my reply while you were answering, and I only saw your answer after I submitted my changes.
